import type { Card } from './types';

export const CARDS: Card[] = [
  // ===================== ДЕНЬ 1 · ПОНЕДЕЛЬНИК · «Базовый уровень» =====================
  // --- Безопасные (7) ---
  { id: '1.1', day: 1, type: 'safe', sender: 'hr@technosphera.by',
    subject: 'Добро пожаловать в команду!',
    body: 'Коллеги, сегодня к нам присоединился новый стажер отдела ИБ. Давайте поможем ему освоиться!',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.2', day: 1, type: 'safe', sender: 'it-helpdesk@technosphera.by',
    subject: 'Доступ к корпоративному принтеру',
    body: 'Для подключения к принтеру на 3-м этаже используйте инструкцию на нашей внутренней Вики: http://wiki.technosphera.by/printer.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.3', day: 1, type: 'safe', sender: 'buhgalteria@technosphera.by',
    subject: 'Сдача таймшитов за прошлую неделю',
    body: 'Напоминаю, что отчеты по часам нужно сдать до 18:00 сегодня, иначе бухгалтерия не сможет рассчитать аванс вовремя.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.4', day: 1, type: 'safe', sender: 'office-manager@technosphera.by',
    subject: 'Заказ пропусков для гостей',
    body: 'Если к вам приходят клиенты или курьеры, оформляйте заявку на пропуск заранее через портал самообслуживания.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.5', day: 1, type: 'safe', sender: 'client-relations@vtb.by',
    subject: 'Запрос на обновление лицензионного соглашения',
    body: 'Здравствуйте! Срок нашего договора на техподдержку истекает. Пришлите, пожалуйста, проект нового соглашения.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.6', day: 1, type: 'safe', sender: 'team-lead@technosphera.by',
    subject: 'Еженедельный созвон разработчиков',
    body: 'Жду всех сегодня в 11:00 в переговорной "Альфа" или по ссылке в корпоративном мессенджере.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '1.7', day: 1, type: 'safe', sender: 'education@technosphera.by',
    subject: 'План обучения на квартал',
    body: 'Коллеги, открыта запись на курсы по повышению квалификации. Выберите интересующее вас направление в личном кабинете.',
    attachment: null, correct: 'pass', explanation: null },
  // --- Фишинг (7) ---
  { id: '1.8', day: 1, type: 'phishing', sender: 'rich-lawyer@yahoo.com',
    subject: 'Срочное уведомление о наследстве',
    body: 'Я представляю интересы покойного миллиардера. Вы являетесь единственным бенефициаром 10 млн долларов. Напишите нам для перевода.',
    attachment: null, correct: 'quarantine',
    explanation: 'Классический спам («нигерийские письма») с бесплатной почты.' },
  { id: '1.9', day: 1, type: 'phishing', sender: 'giveaway@ton-telegram-free.xyz',
    subject: 'Поздравляем! Вы выиграли 500 TON',
    body: 'Ваш аккаунт выбран случайным образом. Заберите ваш выигрыш прямо сейчас, перейдя по ссылке: http://ton-claim-free.xyz.',
    attachment: null, correct: 'quarantine',
    explanation: 'Обещания легких денег на неизвестном домене .xyz.' },
  { id: '1.10', day: 1, type: 'phishing', sender: 'manager@cheap-pills-shop.com',
    subject: 'Скидка 80% на витамины для продуктивности',
    body: 'Устали на работе? Наши новые капсулы улучшают память и внимание. Закажите прямо сейчас с бесплатной доставкой.',
    attachment: null, correct: 'quarantine',
    explanation: 'Нежелательная реклама медицинских товаров (спам).' },
  { id: '1.11', day: 1, type: 'phishing', sender: 'support@casino-vip-royal.net',
    subject: 'Ваш бездепозитный бонус уже начислен',
    body: 'Дарим 1000 рублей на игровой счет всем новым пользователям. Испытайте удачу прямо сейчас!',
    attachment: null, correct: 'quarantine',
    explanation: 'Реклама азартных игр на рабочем месте.' },
  { id: '1.12', day: 1, type: 'phishing', sender: 'hr-recbyiter-world@outlook.com',
    subject: 'Работа на дому: от 5000 рублей в день',
    body: 'Ищем сотрудников для простой подработки. Занятость — 2 часа в день. Перейдите по ссылке для связи с менеджером в Telegram.',
    attachment: null, correct: 'quarantine',
    explanation: 'Сомнительное предложение работы с публичного ящика outlook.com.' },
  { id: '1.13', day: 1, type: 'phishing', sender: 'promo@super-travel-agency.by',
    subject: 'Горящие туры на Мальдивы за 15 000 рублей!',
    body: 'Только сегодня! Ошибочный тариф авиакомпании. Успейте забронировать свой лучший отпуск по ссылке.',
    attachment: null, correct: 'quarantine',
    explanation: 'Слишком заниженная цена – уловка для кражи данных банковских карт.' },
  { id: '1.14', day: 1, type: 'phishing', sender: 'support@fast-antivibys-free.com',
    subject: 'Ваш компьютер заражен 3 вирусами!',
    body: 'Система безопасности обнаружила критические угрозы на вашем ПК. Срочно скачайте наш бесплатный антивирус для очистки.',
    attachment: null, correct: 'quarantine',
    explanation: 'Запугивание пользователя с целью заставить его скачать вредоносное ПО (Malvertising).' },

  // ===================== ДЕНЬ 2 · ВТОРНИК · «Дьявол в деталях» =====================
  // --- Безопасные (7) ---
  { id: '2.1', day: 2, type: 'safe', sender: 'no-reply@yandex.by',
    subject: 'Вход в ваш аккаунт Яндекс ID',
    body: 'Успешный вход с нового устройства (Windows, Браузер Chrome, Москва). Если это были вы, делать ничего не нужно.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.2', day: 2, type: 'safe', sender: 'support@gosuslugi.by',
    subject: 'Заявление на замену загранпаспорта принято',
    body: 'Ваше заявление принято ведомством. Статус рассмотрения вы можете отслеживать в личном кабинете Госуслуг.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.3', day: 2, type: 'safe', sender: 'news@github.com',
    subject: 'Что нового в GitHub Actions',
    body: 'Делимся главными обновлениями нашей платформы автоматизации за прошедший месяц. Читайте наш блог.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.4', day: 2, type: 'safe', sender: 'accounting@belarusbank.by',
    subject: 'Выписка по расчетному счету за вчерашний день',
    body: 'Уважаемый клиент, во вложении выписка по счету вашей организации. Спасибо, что пользуетесь услугами Беларусбанка.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.5', day: 2, type: 'safe', sender: 'client-service@belpost.by',
    subject: 'Ваш заказ № 192837 принят в работу',
    body: 'Посылка от отправителя "Магазин Книг" отправлена. Ожидаемая дата доставки – четверг. Отследить заказ можно на нашем официальном сайте Белпочты.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.6', day: 2, type: 'safe', sender: 'hr-portal@technosphera.by',
    subject: 'Ваша заявка на отпуск согласована',
    body: 'Руководитель одобрил ваш отпуск со следующего понедельника. Документы автоматически направлены в отдел кадров.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '2.7', day: 2, type: 'safe', sender: 'sales@officeton.by',
    subject: 'Подтверждение заказа канцелярии № 5521',
    body: 'Заказ оформлен. Доставка запланирована на завтра, с 10:00 до 14:00. Спасибо за покупку в Офистон!',
    attachment: null, correct: 'pass', explanation: null },
  // --- Фишинг (7) ---
  { id: '2.8', day: 2, type: 'phishing', sender: 'support@yandx.by',
    subject: 'Критическая ошибка синхронизации почты',
    body: 'Ваш ящик заблокирован для отправки писем. Чтобы восстановить доступ, авторизуйтесь заново на портале http://mail-yandx.by.',
    attachment: null, correct: 'quarantine',
    explanation: 'Тайпосквоттинг: домен yandx.by подделан под yandex.by.' },
  { id: '2.9', day: 2, type: 'phishing', sender: 'chief-accountant@technosfere.by',
    subject: 'Изменение реквизитов для выплаты зарплаты',
    body: 'В связи со сменой обслуживающего банка, всем сотрудникам нужно срочно обновить реквизиты карт по ссылке.',
    attachment: null, correct: 'quarantine',
    explanation: 'Домен technosfere.by подделан под technosphera.by.' },
  { id: '2.10', day: 2, type: 'phishing', sender: 'security@belarusbank-online.by',
    subject: 'Ограничение транзакций по счету',
    body: 'Мы зафиксировали подозрительную активность. Доступ к операциям ограничен. Для разблокировки обновите ваш токен безопасности.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельный домен-двойник банка (belarusbank-online.by).' },
  { id: '2.11', day: 2, type: 'phishing', sender: 'info@nalog-gov.by.com',
    subject: 'Внеплановая налоговая проверка вашей компании',
    body: 'Министерство по налогам и сборам выявило несоответствия. Ознакомьтесь с постановлением на портале: http://nalog-by-control.ru.',
    attachment: null, correct: 'quarantine',
    explanation: 'Домен заканчивается на .by.com, а ссылка ведёт на .ru — не госресурс.' },
  { id: '2.12', day: 2, type: 'phishing', sender: 'admin@google-verify-account.com',
    subject: 'Удаление неактивных аккаунтов Google Workspace',
    body: 'Ваша корпоративная почта не прошла верификацию безопасности. Нажмите "Подтвердить пароль" в течение 24 часов, чтобы избежать удаления.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельный домен, имитирующий Google, + требование ввести пароль.' },
  { id: '2.13', day: 2, type: 'phishing', sender: 'hr-survey@technosphera-hr.com',
    subject: 'Опрос для сотрудников: оценка лояльности',
    body: 'Пожалуйста, пройдите анонимный опрос о работе нашего руководства на портале http://technosphera-hr.com.',
    attachment: null, correct: 'quarantine',
    explanation: 'Внешний домен technosphera-hr.com маскируется под компанию.' },
  { id: '2.14', day: 2, type: 'phishing', sender: 'update@java-runtime-upgrade.org',
    subject: 'Критическое обновление безопасности Java Runtime Environment',
    body: 'Ваша версия Java устарела и содержит уязвимость нулевого дня. Скачайте сертифицированное обновление для вашей ОС.',
    attachment: null, correct: 'quarantine',
    explanation: 'Подложный домен обновлений, попытка подсунуть вредоносное ПО.' },

  // ===================== ДЕНЬ 3 · СРЕДА · «Эмоциональные качели» =====================
  // --- Безопасные (7) ---
  { id: '3.1', day: 3, type: 'safe', sender: 'qa-lead@technosphera.by',
    subject: 'КРИТИЧЕСКИЙ БАГ: Падает регистрация новых пользователей',
    body: 'Коллеги, на продакшене баг, новые юзеры не могут войти в ЛК. Нужно срочно откатить вчерашний релиз! Кто может помочь?',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.2', day: 3, type: 'safe', sender: 'director@technosphera.by',
    subject: 'Результаты квартального собрания директоров',
    body: 'Поздравляю всех с отличными показателями! Мы выросли на 20% по сравнению с прошлым кварталом. Полный отчет выложу в Confluence.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.3', day: 3, type: 'safe', sender: 'pr-team@technosphera.by',
    subject: 'Выбор темы для новогоднего корпоратива',
    body: 'Мы подготовили три варианта тематики вечеринки. Голосуйте на внутреннем портале до конца недели, нам важно ваше мнение!',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.4', day: 3, type: 'safe', sender: 'lawyers@technosphera.by',
    subject: 'Внесение изменений в NDA с контрагентами',
    body: 'Юристы обновили шаблон соглашения о конфиденциальности. Пожалуйста, используйте только новую версию из папки на общем диске.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.5', day: 3, type: 'safe', sender: 'it-security@technosphera.by',
    subject: 'Плановая смена паролей в эту пятницу',
    body: 'Напоминаем, что согласно политике безопасности, раз в 90 дней необходимо обновлять пароли. Вы получите стандартное системное уведомление.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.6', day: 3, type: 'safe', sender: 'analytics@belinvest-group.by',
    subject: 'Запрос на проведение аудита информационной безопасности',
    body: 'Добрый день! Нам рекомендовали вашу компанию как экспертов. Пришлите ваши условия проведения внешнего пентеста.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '3.7', day: 3, type: 'safe', sender: 'purchasing@technosphera.by',
    subject: 'Оплата счетов за облачную инфраструктуру',
    body: 'Бухгалтерия оплатила счета за хостинг серверов на следующий месяц. Проблем с доступностью сервисов не ожидается.',
    attachment: null, correct: 'pass', explanation: null },
  // --- Фишинг (7) ---
  { id: '3.8', day: 3, type: 'phishing', sender: 'sudebnie-ispolniteli@minjust-by.com',
    subject: 'СРОЧНО: Постановление о наложении ареста на ваше имущество',
    body: 'В связи с неуплатой пошлины, вынесено решение об аресте ваших счетов. Срочно ознакомьтесь с делом, чтобы избежать блокировки: http://minjust-case-check.by.',
    attachment: null, correct: 'quarantine',
    explanation: 'Давление страхом и срочностью + поддельный «государственный» домен.' },
  { id: '3.9', day: 3, type: 'phishing', sender: 'alert@google-workspace-verify.by',
    subject: 'Внимание: Ваша учетная запись будет удалена через 30 минут!',
    body: 'Обнаружена попытка рассылки спама с вашего аккаунта. Если это ошибка, подтвердите владение профилем прямо сейчас: http://verify-my-account-now.com.',
    attachment: null, correct: 'quarantine',
    explanation: 'Искусственная срочность (30 минут) и подложные домены.' },
  { id: '3.10', day: 3, type: 'phishing', sender: 'bonus-hr@technosphera-rewards.by',
    subject: 'Утверждены списки на выплату годовой премии 1000 BYN',
    body: 'Руководство решило поощрить лучших сотрудников. Найдите свою фамилию в списке получателей и подтвердите банковские реквизиты: http://bonus-technosphera.by.',
    attachment: null, correct: 'quarantine',
    explanation: 'Приманка деньгами + внешний домен, просит банковские реквизиты.' },
  { id: '3.11', day: 3, type: 'phishing', sender: 'delivery-failed@belpost-delivery.com',
    subject: 'Ваша посылка задерживается из-за неоплаченной пошлины',
    body: 'Посылка прибыла на склад Белпочты, но не может быть доставлена. Оплатите пошлину в размере 5 рублей для продолжения доставки.',
    attachment: null, correct: 'quarantine',
    explanation: 'Классическая схема «доплати за посылку» на поддельном домене.' },
  { id: '3.12', day: 3, type: 'phishing', sender: 'former-colleague@gmail.com',
    subject: 'Вся правда о руководстве компании ТехноСфера!',
    body: 'Привет! Я собрал все доказательства черной бухгалтерии нашей фирмы и выложил их на диск. Посмотри, пока они не заставили меня удалить: http://yandex-disk-leak.by/file.',
    attachment: null, correct: 'quarantine',
    explanation: 'Игра на любопытстве/интриге, ссылка на подложный «диск».' },
  { id: '3.13', day: 3, type: 'phishing', sender: 'advokat-office@court-appeal.by',
    subject: 'Исковое заявление о нарушении авторских прав вашей компанией',
    body: 'К нам обратился правообладатель. Вы незаконно используете его изображения на вашем сайте. Если вы не удалите их в течение суток, мы подаем в суд. Копия иска по ссылке.',
    attachment: null, correct: 'quarantine',
    explanation: 'Юридическая угроза с дедлайном — давление страхом.' },
  { id: '3.14', day: 3, type: 'phishing', sender: 'security-alert@technosphera-it-support.by',
    subject: 'УГРОЗА ВЗЛОМА: Обнаружено вредоносное ПО на вашем ПК',
    body: 'Ваш рабочий компьютер рассылает вирусы во внутреннюю сеть компании. Немедленно запустите утилиту очистки с нашего сервера, иначе мы отключим вас от сети через 15 минут.',
    attachment: null, correct: 'quarantine',
    explanation: 'Псевдо-техподдержка + ультиматум по времени, внешний домен.' },

  // ===================== ДЕНЬ 4 · ЧЕТВЕРГ · «Опасные файлы» =====================
  // --- Безопасные (7) ---
  { id: '4.1', day: 4, type: 'safe', sender: 'partner@belstroy.by',
    subject: 'Согласованный договор неразглашении (NDA)',
    body: 'Высылаем подписанную с нашей стороны копию соглашения о конфиденциальности. Ждем ваш экземпляр.',
    attachment: 'NDA_BelStroy_Signed.pdf', correct: 'pass', explanation: null },
  { id: '4.2', day: 4, type: 'safe', sender: 'finance@technosphera.by',
    subject: 'Итоговый отчет о расходах за прошлый квартал',
    body: 'Коллеги, во вложении сводная таблица по расходам отделов. Все вопросы присылайте в ответном письме.',
    attachment: 'Expenses_Q3_Report.xlsx', correct: 'pass', explanation: null },
  { id: '4.3', day: 4, type: 'safe', sender: 'sysadmin@technosphera.by',
    subject: 'Логи ошибок почтового сервера',
    body: 'Посмотри, пожалуйста, выгрузку логов за вчерашний вечер. Был кратковременный сбой в отправке внешних писем.',
    attachment: 'server_error_log.txt', correct: 'pass', explanation: null },
  { id: '4.4', day: 4, type: 'safe', sender: 'marketing@technosphera.by',
    subject: 'Презентация нового продукта для вебинара',
    body: 'Высылаем слайды для завтрашнего выступления. Посмотрите, все ли шрифты отображаются корректно.',
    attachment: 'Product_Webinar_v2.pptx', correct: 'pass', explanation: null },
  { id: '4.5', day: 4, type: 'safe', sender: 'design@technosphera.by',
    subject: 'Иконки для мобильного приложения',
    body: 'Привет! Подготовил пак иконок в векторе для разработчиков. Форматы PNG и SVG внутри архива.',
    attachment: 'App_Icons_Pack.zip', correct: 'pass', explanation: null },
  { id: '4.6', day: 4, type: 'safe', sender: 'editor@creative-studio.by',
    subject: 'Макет главной страницы нашего сайта',
    body: 'Здравствуйте! Разработали первый вариант дизайна главной страницы. Оцените цветовую гамму.',
    attachment: 'Homepage_Mockup_Final.png', correct: 'pass', explanation: null },
  { id: '4.7', day: 4, type: 'safe', sender: 'no-reply@quidox.by',
    subject: 'Вам отправлен закрывающий акт по договору',
    body: 'Поступил новый документ в системе ЭДО Quidox. Копия акта сверки во вложении.',
    attachment: 'Act_Sverki_Quidox.pdf', correct: 'pass', explanation: null },
  // --- Фишинг (7) ---
  { id: '4.8', day: 4, type: 'phishing', sender: 'photographer-event@mail.ru',
    subject: 'Фотографии с нашего вчерашнего праздника!',
    body: 'Всем привет! Отлично повеселились. Фотографии залил в архив, качайте скорее!',
    attachment: 'Corporate_Party_Best_Photos.zip', correct: 'quarantine',
    explanation: 'Неожиданный архив от неизвестного внешнего отправителя — типичный вектор заражения.' },
  { id: '4.9', day: 4, type: 'phishing', sender: 'billing-department@mns-control-portal.by',
    subject: 'Требование об уплате налоговой задолженности организации',
    body: 'Министерство по налогам и сборам выставило требование о погашении пени. Документ с электронной подписью прикреплен ниже.',
    attachment: 'MNS_Tax_Demand_Report.pdf.bat', correct: 'quarantine',
    explanation: 'Двойное расширение .pdf.bat — под видом PDF исполняемый bat-скрипт.' },
  { id: '4.10', day: 4, type: 'phishing', sender: 'tender-platform@goszakupki-by.com',
    subject: 'Участие в закрытом государственном тендере ИТ-услуг',
    body: 'Ваша компания прошла предварительный отбор. Техническое задание прикреплено к письму. Для корректного отображения таблиц обязательно включите макросы при открытии файла.',
    attachment: 'Tender_Specs_Techno.docm', correct: 'quarantine',
    explanation: 'Файл .docm с макросами + просьба «включить макросы» — запуск вредоносного кода.' },
  { id: '4.11', day: 4, type: 'phishing', sender: 'accounting-support@nalog-gov-by.com',
    subject: 'Акт сверки взаиморасчетов по налогам за 2024 год',
    body: 'Направляем официальный акт сверки. Просим подписать и прислать скан-копию.',
    attachment: 'Akt_Sverki_2024.xlsx.exe', correct: 'quarantine',
    explanation: 'Двойное расширение .xlsx.exe — исполняемый файл под видом таблицы.' },
  { id: '4.12', day: 4, type: 'phishing', sender: 'candidate-hr@job-agency-premium.by',
    subject: 'Резюме Senior DevOps инженера на вашу вакансию',
    body: 'Здравствуйте! Нашли идеального кандидата. Опыт работы и примеры его скриптов автоматизации — во вложении.',
    attachment: 'CV_DevOps_Specialist.zip', correct: 'quarantine',
    explanation: 'Архив «резюме» от неизвестного агентства — может содержать вредонос.' },
  { id: '4.13', day: 4, type: 'phishing', sender: 'finance-update@technosphera-billing.by',
    subject: 'Обновленная форма отчета о представительских расходах',
    body: 'Коллеги, изменились правила подачи отчетов. Пользуйтесь только этой интерактивной формой Excel с авторасчетом сумм.',
    attachment: 'Expenses_Form_2025.xlsm', correct: 'quarantine',
    explanation: 'Внешний домен-двойник + .xlsm (макросы Excel).' },
  { id: '4.14', day: 4, type: 'phishing', sender: 'support@google-chrome-updater.com',
    subject: 'Срочное обновление безопасности для вашего браузера',
    body: 'Обнаружена критическая уязвимость удаленного выполнения кода. Установите исправление безопасности вручную из вложения.',
    attachment: 'chrome_patch_security.exe', correct: 'quarantine',
    explanation: 'Исполняемый .exe «обновление браузера» — браузеры так не обновляют.' },

  // ===================== ДЕНЬ 5 · ПЯТНИЦА · «Пятничный завал» =====================
  // --- Безопасные (базовые 7) ---
  { id: '5.1', day: 5, type: 'safe', sender: 'legal-dept@technosphera.by',
    subject: 'Согласование договора с новым арендодателем',
    body: 'Коллеги, юристы проверили договор аренды нового офиса. Просим согласовать документ до конца дня.',
    attachment: 'Office_Lease_Agreement_Final.pdf', correct: 'pass', explanation: null },
  { id: '5.2', day: 5, type: 'safe', sender: 'it-admin@technosphera.by',
    subject: 'Проведение технических работ на выходных',
    body: 'В субботу с 02:00 до 06:00 корпоративная почта может быть недоступна из-за планового обновления серверов.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.3', day: 5, type: 'safe', sender: 'cfo@technosphera.by',
    subject: 'Утвержденная смена бюджетов отделов на Q4',
    body: 'Направляю официальный финансовый план на следующий квартал. Ознакомьтесь с вашими лимитами.',
    attachment: 'Q4_Financial_Plan_Approved.pdf', correct: 'pass', explanation: null },
  { id: '5.4', day: 5, type: 'safe', sender: 'news@technosphera.by',
    subject: 'Дайджест ИТ-новостей нашей компании за месяц',
    body: 'Привет, команда! Собрали все наши победы за октябрь в один выпуск. Приятного чтения на выходных!',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.5', day: 5, type: 'safe', sender: 'jira@technosphera-jira.by',
    subject: '[JIRA] На вас назначена задача TS-4055',
    body: 'Пользователь TeamLead назначил на вас задачу: "Проверить настройки фаервола на тестовом сервере". Ссылка на задачу во внутренней сети.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.6', day: 5, type: 'safe', sender: 'no-reply@portal.gov.by',
    subject: 'Вам одобрен доступ к личному кабинету юрлица',
    body: 'Доступ к личному кабинету успешно предоставлен ведомством. Вы можете зайти в него с помощью вашей цифровой подписи.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.7', day: 5, type: 'safe', sender: 'partner-security@kaspersky.by',
    subject: 'Продление партнерского сертификата ИБ',
    body: 'Поздравляем! Ваша компания подтвердила статус авторизованного партнера в регионе Беларусь. Оригинал сертификата во вложении.',
    attachment: 'Partner_Certificate_Kaspersky_2025.pdf', correct: 'pass', explanation: null },
  // --- Фишинг (базовые 7) ---
  { id: '5.8', day: 5, type: 'phishing', sender: 'it-security@outlook-microsoft-office365.com',
    subject: 'Настройка двухфакторной аутентификации Office 365',
    body: 'Для предотвращения несанкционированного доступа к вашей корпоративной почте, отсканируйте этот QR-код камерой мобильного телефона и введите пароль.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельный домен под Microsoft + фишинг через QR-код (quishing).' },
  { id: '5.9', day: 5, type: 'phishing', sender: 'general-director.technosphera@gmail.com',
    subject: 'КОНФИДЕНЦИАЛЬНО: Срочный платеж за лицензии',
    body: 'Я сейчас на важной встрече с инвесторами, говорить не могу. Нужно срочно перевести 5000 BYN на счет субподрядчика. Документы прикреплены. Никому не говори, это конфиденциальный проект.',
    attachment: null, correct: 'quarantine',
    explanation: 'Мошенничество «письмо от руководителя» (BEC/CEO fraud) с бесплатной почты.' },
  { id: '5.10', day: 5, type: 'phishing', sender: 'no-reply@github-technosphera.by',
    subject: 'Критическая уязвимость в репозитории проекта',
    body: 'В вашем коде обнаружена утечка приватного ключа доступа к AWS. Срочно авторизуйтесь через систему контроля версий, чтобы предотвратить компрометацию данных: http://github-technosphera.by/auth.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельный домен, имитирующий GitHub, ведёт на страницу кражи учётных данных.' },
  { id: '5.11', day: 5, type: 'phishing', sender: 'admin@technosphera-hr-portal.by',
    subject: 'Плановая аттестация сотрудников ИТ-департамента',
    body: 'Каждому сотруднику необходимо подтвердить свою квалификацию. Пройдите обязательный тест на портале до конца рабочего дня, иначе вам будет вынесено предупреждение: http://technosphera-hr-portal.by.',
    attachment: null, correct: 'quarantine',
    explanation: 'Внешний домен-двойник + давление дедлайном.' },
  { id: '5.12', day: 5, type: 'phishing', sender: 'notification@teams-microsoft-online.by',
    subject: 'У вас 3 пропущенных звонка в Microsoft Teams',
    body: 'Пользователь Анна Сергеевна (Руководитель отдела) пыталась связаться с вами. Ознакомьтесь с деталями пропущенного вызова и прослушайте голосовое сообщение в личном кабинете.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельное уведомление Teams с подставленным именем руководителя.' },
  { id: '5.13', day: 5, type: 'phishing', sender: 'support@yandex-cloud-billing.by',
    subject: 'Превышение лимита использования ресурсов Яндекс Облака',
    body: 'Внимание: ваши тестовые серверы превысили лимит бесплатного тарифа. Списание средств произойдет через 12 часов. Для отключения платных опций авторизуйтесь в консоли управления.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельный биллинг-домен + угроза списания денег для срочной авторизации.' },
  { id: '5.14', day: 5, type: 'phishing', sender: 'newsletter@it-news-weekly.by',
    subject: 'Дайджест ИТ-безопасности: Главные взломы 2025 года',
    body: 'Интересная подборка статей для специалистов. Если вы больше не хотите получать наши письма, нажмите кнопку Отписаться от рассылки.',
    attachment: null, correct: 'quarantine',
    explanation: 'Незапрошенная рассылка; кнопка «Отписаться» — приманка для клика/подтверждения адреса.' },
  // --- Дополнительные безопасные (5) ---
  { id: '5.15', day: 5, type: 'safe', sender: 'billing@hoster.by',
    subject: 'Продление доменного имени technosphera.by',
    body: 'Уважаемый клиент, срок регистрации вашего доменного имени истекает через 14 дней. Счет на оплату сформирован в вашем личном кабинете hoster.by.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.16', day: 5, type: 'safe', sender: 'corporate@priorbank.by',
    subject: 'Плановый выпуск корпоративных карт Priorback-Visa',
    body: 'Добрый день! Карты для ваших новых сотрудников изготовлены и доставлены в отделение по адресу: г. Минск, ул. Кропоткина, 91. Ждем вашего представителя.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.17', day: 5, type: 'safe', sender: 'hr@technosphera.by',
    subject: 'Сбор заявок на летний тимбилдинг в Нарочанском парке',
    body: 'Коллеги, мы планируем выезд на выходные в усадьбу на Нарочи. Пожалуйста, проголосуйте за удобные даты в нашей внутренней системе до конца этой недели.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.18', day: 5, type: 'safe', sender: 'info@park.by',
    subject: 'Запрос отчетности резидентов ПВТ за прошедшее полугодие',
    body: 'Уважаемые резиденты Парка высоких технологий! Напоминаем о необходимости предоставления статистической отчетности согласно установленной форме. Шаблоны доступны на официальном портале администрации.',
    attachment: null, correct: 'pass', explanation: null },
  { id: '5.19', day: 5, type: 'safe', sender: 'dev-lead@technosphera.by',
    subject: 'Срочный код-ревью пул-реквеста перед релизом',
    body: 'Привет! Посмотри, пожалуйста, мои изменения в ветке фикса авторизации. Ссылка на наш локальный гитлаб: http://git.technosphera.by/project/auth/pulls/12.',
    attachment: null, correct: 'pass', explanation: null },
  // --- Дополнительные фишинговые (5) ---
  { id: '5.20', day: 5, type: 'phishing', sender: 'support@belpost-tracking.by.com',
    subject: 'Ваше отправление задержано на таможенном терминале «Минск-2»',
    body: 'Для завершения оформления международной посылки необходимо оплатить таможенную пошлину в размере 12.50 BYN. Оплатить онлайн и подтвердить адрес можно по ссылке.',
    attachment: null, correct: 'quarantine',
    explanation: 'Домен .by.com маскируется под Белпочту; схема «доплати пошлину».' },
  { id: '5.21', day: 5, type: 'phishing', sender: 'security@belarusbank-secure.by',
    subject: 'Подозрительный вход в ваш личный кабинет Беларусбанк',
    body: 'Зафиксирована попытка перевода средств на карту зарубежного банка. В целях безопасности транзакция приостановлена. Срочно отмените операцию по ссылке: http://belarusbank-safety-portal.by.',
    attachment: null, correct: 'quarantine',
    explanation: 'Поддельные банковские домены-двойники + давление страхом потери денег.' },
  { id: '5.22', day: 5, type: 'phishing', sender: 'info@htp-administration.com',
    subject: 'Новые налоговые льготы для резидентов ПВТ в 2025 году',
    body: 'Администрация Парка подготовила разъяснения по изменениям в налоговом законодательстве для ИТ-компаний. Подробный регламент во вложении.',
    attachment: 'HTP_Tax_Changes_2025.zip', correct: 'quarantine',
    explanation: 'Внешний домен .com «под администрацию ПВТ» + подозрительный архив.' },
  { id: '5.23', day: 5, type: 'phishing', sender: 'billing@minskenergo-by.com',
    subject: 'Акт сверки расчетов за электроэнергию и выставленный счет',
    body: 'Уважаемый потребитель! Просим вас ознакомиться с начислениями за арендуемые помещения за текущий месяц и оплатить задолженность.',
    attachment: 'Minskenergo_Invoice_Q3.pdf.exe', correct: 'quarantine',
    explanation: 'Двойное расширение .pdf.exe — исполняемый файл под видом счёта.' },
  { id: '5.24', day: 5, type: 'phishing', sender: 'admin@portal-gov-by.com',
    subject: 'Срочное обновление сертификатов ЭЦП ГосСУОК',
    body: 'В связи с техническим обновлением корневых сертификатов Республики Беларусь, всем юридическим лицам требуется установить новый список отзывов из вложения для работы с порталом декларирования.',
    attachment: 'Sertificates_Update_2025.js', correct: 'quarantine',
    explanation: 'Вложение .js (исполняемый скрипт) под видом «обновления сертификатов».' },
];
